### ISSUE TITLE
请教空气果1使用easylink链接不了wifi

### ISSUE THREAD

**Issue by innx2020** [billhu1996/Airnut#1]
是否有解决方案，感谢

**Comment by MagicSchooliOS** [comment]
好像是iOS版本连不上，找一个Android手机，用这个[地址https://www.mxchip.com/easylink/](https://www.mxchip.com/easylink/)下载的再试试，还有提示连接失败，但是可能已经连上了，可以再路由器后台看看

**Comment by billhu1996** [comment]
1 iOS版本的easylink好像有问题连不上，换Android试试
2 用这个地址的Android版本试试，其他版本可能不行https://www.mxchip.com/easylink/
3 空气果提示连接失败，但实际可能已经连接，去路由器后台看看有没有新设备连入。
