### ISSUE TITLE
請問是如何更新的呢?

### ISSUE THREAD

**Issue by mcdull** [billhu1996/Airnut#2]
我一直是用空氣果服務器截取 json 接入HA, 但它服務器不穩定, 且非常不安全, 希望有其他方法接入.
試了這個插件, 第一次是可以抓到數據, 但我移除了我原來的 entity 重啟後, 就再沒有更新了, 都是 unknown.

空氣果 IP 是有的, 但如觸發 airnut 訪問 apn.airnut.com 呢?
再次謝謝開發這個插件.

is_night_update: true  (所以應該不是這個問題)

**Comment by mcdull** [comment]
剛找到了, 加入 scan_interval: 90
這樣 3分鐘就會更新一次.
但問題來了, 這個空氣果光的很, 而每次更新, 就會出一個動畫, 就算10分鐘更新一次, 都非常煩擾.
有設定可以不顯示動畫嗎?

**Comment by billhu1996** [comment]
您好，首先感谢您使用本插件。

我写这个插件时候，官方服务已经很不稳定了。在服务可用的时候，手动在APP上更新信息时，我抓包看了一下服务端对空气果的信息。插件就是参考这个信息和空气果通信的。所以这解释了为什么会亮光。这也是为什么我会设置一个夜间是否更新的逻辑，在夜间不触发更新。

如果想要解决，就不得不看官方服务的自动同步原理。也就是在官方服务能用的时候抓包查看通信消息。

还有，这个插件有个小问题，就是在关闭服务的时候无法释放端口，现象就是重启ha时，每隔一次启动失败一次，ha日志中有“server got [Errno 98] Address in use”错误。临时的解决办法是再重启一次。

**Comment by mcdull** [comment]
剛發了個PR給你, 你看看是否能解決那個小問題, 我也是每次要重啟比較煩

Bill Hu ***@***.***> 於 2021年10月27日週三 下午2:48寫道：
